data=
{
	"COMP3D_COMMIT" : "N/A",
	"COMP3D_COPYRIGHT" : "Copyright 1992-2024 IGN France www.ign.fr",
	"COMP3D_LICENSE" : "Provided with absolutely no warranty, under GPLv3 license",
	"COMP3D_OPTIONS" : "QT GUI RES AUTO ",
	"COMP3D_REPO" : "https://github.com/IGNF/Comp3D",
	"COMP3D_VERSION" : "COMP3D v5.24dev-PROJ 9.3.1-linux",
	"all_data_files" : 
	{
		"0" : "bat4.cor",
		"1" : "bat4.obs"
	},
	"all_forbidden_point_names" : null,
	"all_point_names" : 
	[
		"S1",
		"S4",
		"PC1",
		"PC2",
		"GYRO",
		"TFLE",
		"PTHN",
		"IGNF",
		"CHSL_E",
		"CHSL_O",
		"VITRY",
		"OBSV",
		"ANFN",
		"BAT4"
	],
	"all_uninitializable_point_names" : null,
	"computation" : 
	{
		"Monte_Carlo_done" : false,
		"all_parameters_names" : 
		[
			"OBSV_x",
			"OBSV_y",
			"IGNF_x",
			"IGNF_y",
			"PTHN_x",
			"PTHN_y",
			"TFLE_x",
			"TFLE_y",
			"VITRY_x",
			"VITRY_y",
			"ANFN_x",
			"ANFN_y",
			"GYRO_x",
			"GYRO_y",
			"GYRO_G0_1",
			"GYRO_G0_2",
			"S1_x",
			"S1_y",
			"S1_G0_1",
			"PC1_x",
			"PC1_y",
			"PC1_G0_1",
			"S4_x",
			"S4_y",
			"S4_G0_1",
			"BAT4_x",
			"BAT4_y",
			"CHSL_E_x",
			"CHSL_E_y",
			"PC2_x",
			"PC2_y",
			"PC2_G0_1",
			"CHSL_O_x",
			"CHSL_O_y"
		],
		"all_sigma0" : 
		[
			2.5351503162540112,
			1.2104424152261961,
			1.210442408610058
		],
		"biggest_ellips" : 0.12104424086100582,
		"chi2_test" : 
		{
			"DOF" : 29,
			"confidence" : 0.98999999999999999,
			"max" : 1.4866648290710325,
			"min" : 0.7443896420164906
		},
		"compensation_done" : true,
		"computation_duration" : "00:00:00.001070",
		"computation_start" : "2025-Aug-01 17:19:21.264574",
		"internal_constraints" : false,
		"internal_constraints_obs" : [],
		"interrupted" : false,
		"inverted_matrix" : true,
		"kernel" : null,
		"messages_computation" : "",
		"messages_read_config" : "",
		"messages_read_data" : "Lecture du COR...<br/>\nLecture du fichier bat4.cor...<br/>\nLecture du OBS...<br/>\nLecture du fichier bat4.obs...<br/>\nMise en place des points...<br/>\n<font color=#FF8000>&nbsp;&nbsp;&nbsp;&nbsp;1 point non initialis\u00e9.</font><br/>\nLecture des donn\u00e9es termin\u00e9e.<br/>\nTous les points sont initialis\u00e9s.<br/>\nD\u00e9viation de la verticale non utilis\u00e9e.<br/>\n",
		"messages_set_least_squares" : "",
		"nbr_active_obs" : 63,
		"nbr_all_obs" : 63,
		"nbr_iterations" : 2,
		"nbr_parameters" : 34,
		"projection" : 
		{
			"center_cartgeocentric" : 
			[
				4200313.8248928636,
				177970.29056886974,
				4780408.8609263832
			],
			"center_geographic" : 
			[
				2.4262118027828778,
				48.861076448281828,
				0.0
			],
			"center_latitude" : 48.861076448281828,
			"earth_model_radius" : 6380980.576358757,
			"geocent_def" : "+proj=geocent",
			"input_proj_EPSG" : 2154,
			"input_proj_def" : "IGNF:LAMB93",
			"input_proj_name" : "RGF93 / Lambert-93",
			"is_georef" : true,
			"latlong_def" : "+proj=latlong",
			"local_center_stereo" : 
			[
				-1.7503009451088541e-10,
				4.2505869333328717e-09,
				0.0
			],
			"local_scale" : 1.0,
			"rot_global2geocentric" : 
			[
				[
					-0.04233273030295235,
					-0.75244151671382997,
					0.65729727206986688
				],
				[
					0.99910356817754264,
					-0.031881483372032816,
					0.027850153911626683
				],
				[
					0.0,
					0.65788702293280554,
					0.75311663443095589
				]
			],
			"stereo_def" : "+proj=sterea +lat_0=48.8610764482818 +lon_0=2.42621180278288 +k_0=1 +x_0=0 +y_0=0"
		},
		"rank_deficiency" : 0,
		"sigma_0_final" : 1.210442408610058,
		"sigma_0_init" : 2.5351503162540112,
		"solver_name" : "N5Eigen14SimplicialLDLTINS_12SparseMatrixIdLi0EiEELi1ENS_11AMDOrderingIiEEEE",
		"unit_name" : "g",
		"use_vertical_deflection" : false
	},
	"config" : 
	{
		"center_latitude" : 48.799999999999997,
		"clean_outputs" : false,
		"compute_type" : 0,
		"convergence_criterion" : 0.001,
		"coord_cov_file" : "",
		"description" : "",
		"display_map" : true,
		"files_unit" : 1,
		"force_iterations" : 0,
		"internal_constraints" : false,
		"invert_matrix" : true,
		"lang" : "fr",
		"local_center" : 
		[
			657903.0,
			6862491.0,
			0.0
		],
		"max_iterations" : 100,
		"misc_metadata" : null,
		"name" : "bat4",
		"nb_digits" : 4,
		"proj_def" : "IGNF:LAMB93",
		"refraction" : 0.12,
		"root_COR_file" : "bat4.cor",
		"root_OBS_file" : "bat4.obs",
		"use_ellips_height" : true,
		"use_proj" : true
	},
	"config_file" : "/home/YMeneroux/Bureau/KitYann/Recherches/Verniquet/verniquet/micro/preparation/bat4/bat4.comp",
	"other_stations" : null,
	"points" : 
	{
		"ANFN" : 
		{
			"code" : 7,
			"code_name" : "2xy ",
			"comment" : "",
			"coord_compensated_cartesian" : 
			[
				1375.8839626990057,
				-1978.354399105627,
				-0.45525120806837549
			],
			"coord_compensated_georef" : 
			[
				659264.31237274176,
				6860502.9137086226,
				0.0
			],
			"coord_compensated_latlong" : 
			[
				2.4449565392674355,
				48.843285066541263,
				0.0
			],
			"coord_init_latlong" : 
			[
				2.4449566566904513,
				48.843285078700127,
				0.0
			],
			"coord_read" : 
			[
				659264.321,
				6860502.915,
				0.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 2,
			"ellips" : 
			{
				"axes" : 
				[
					[
						0.028218537413880022,
						103.81061241577214,
						0.0
					],
					[
						0.01674777335517811,
						3.810612415772114,
						0.0
					],
					[
						0.0,
						0.0,
						100.0
					]
				],
				"matrix" : 
				[
					0.00054221665959759951,
					-2.1021715712591898e-05,
					0.0,
					0.00019269680447377212,
					0.0,
					0.0
				],
				"sigmas" : 
				[
					0.028185812570045158,
					0.016802789527374466,
					0.0
				]
			},
			"file_id" : 0,
			"nbr_active_obs" : 3,
			"number" : 12,
			"params" : 
			{
				"ANFN_x" : 
				{
					"rank" : 10,
					"sigma" : 0.028185812570045158,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 1375.8839626680515
				},
				"ANFN_y" : 
				{
					"rank" : 11,
					"sigma" : 0.016802789527374466,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : -1978.3543991971655
				}
			},
			"shift_from_read" : 
			[
				-0.0086272582411766052,
				-0.0012913774698972702,
				0.0
			],
			"sigmas_init" : 
			[
				0.025999999999999999,
				0.014,
				0.0
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 2,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : -1,
							"comment" : "",
							"computed_value" : 1375.8839626680515,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "ANFN",
							"instrument_height" : 0.0,
							"line" : 16,
							"nabla" : 0.23962357040459248,
							"normalized_residual" : -0.33148627917748508,
							"number" : 24,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 19.790434970769311,
							"obs_zen" : 0.0,
							"original_value" : 1375.8925813113101,
							"rank" : 24,
							"residual" : -0.0086186432586146111,
							"residual_std" : -0.37012845661208466,
							"sigma_a_posteriori" : 0.023285546152014547,
							"sigma_abs" : 0.025999999999999999,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.011566474847696701,
							"sigma_total" : 0.025999999999999999,
							"standardized_residual" : -0.745140016478823,
							"target_height" : 0.0,
							"to" : "ANFN",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -2,
							"comment" : "",
							"computed_value" : -1978.3543991971655,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "ANFN",
							"instrument_height" : 0.0,
							"line" : 16,
							"nabla" : 0.44215321502238575,
							"normalized_residual" : -0.096733520194902667,
							"number" : 25,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 1.6853038399121778,
							"obs_zen" : 0.0,
							"original_value" : -1978.3530449278828,
							"rank" : 25,
							"residual" : -0.0013542692827286373,
							"residual_std" : -0.097559096947684748,
							"sigma_a_posteriori" : 0.013881527454634527,
							"sigma_abs" : 0.014,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.0018174695392847379,
							"sigma_total" : 0.014,
							"standardized_residual" : -0.74514001663081941,
							"target_height" : 0.0,
							"to" : "ANFN",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						}
					],
					"params" : null,
					"type" : "simple"
				}
			]
		},
		"BAT4" : 
		{
			"code" : 6,
			"code_name" : "2-- ",
			"comment" : "",
			"coord_compensated_cartesian" : 
			[
				131.22414121648868,
				321.13731298365281,
				-0.0094400991424379299
			],
			"coord_compensated_georef" : 
			[
				658036.54059756012,
				6862811.1422200836,
				0.0
			],
			"coord_compensated_latlong" : 
			[
				2.4280003076541687,
				48.863964176197186,
				0.0
			],
			"coord_init_latlong" : 
			[
				2.4280003448815806,
				48.863964193106142,
				0.0
			],
			"coord_read" : 
			[
				658036.5433422369,
				6862811.1440804545,
				0.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 2,
			"ellips" : 
			{
				"axes" : 
				[
					[
						0.0089270362468341011,
						27.141443782398834,
						0.0
					],
					[
						0.0072920145114846813,
						127.14144378239899,
						0.0
					],
					[
						0.0,
						0.0,
						100.0
					]
				],
				"matrix" : 
				[
					3.9386880595653293e-05,
					6.8147519044377801e-06,
					0.0,
					5.1295686624955612e-05,
					0.0,
					0.0
				],
				"sigmas" : 
				[
					0.0075966116340936696,
					0.0086693104379036833,
					0.0
				]
			},
			"file_id" : -1,
			"nbr_active_obs" : 5,
			"number" : 13,
			"params" : 
			{
				"BAT4_x" : 
				{
					"rank" : 25,
					"sigma" : 0.0075966116340936696,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 131.22414121643138
				},
				"BAT4_y" : 
				{
					"rank" : 26,
					"sigma" : 0.0086693104379036833,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 321.13731298819437
				}
			},
			"shift_from_read" : 
			[
				-0.0027446767780929804,
				-0.001860370859503746,
				0.0
			],
			"sigmas_init" : 
			[
				0.0,
				0.0,
				0.0
			],
			"stations" : []
		},
		"CHSL_E" : 
		{
			"code" : 7,
			"code_name" : "2xy ",
			"comment" : "",
			"coord_compensated_cartesian" : 
			[
				766.25683970589569,
				-2085.1259772261519,
				-0.38711819991794982
			],
			"coord_compensated_georef" : 
			[
				658653.99642577535,
				6860400.5911083296,
				0.0
			],
			"coord_compensated_latlong" : 
			[
				2.4366509157500769,
				48.842325999662982,
				0.0
			],
			"coord_init_latlong" : 
			[
				2.4366509099595146,
				48.842325998661444,
				0.0
			],
			"coord_read" : 
			[
				658653.99600000004,
				6860400.591,
				0.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 2,
			"ellips" : 
			{
				"axes" : 
				[
					[
						0.0048322269133759506,
						198.91411949729041,
						0.0
					],
					[
						0.0035781230965644846,
						98.914119497290415,
						0.0
					],
					[
						0.0,
						0.0,
						100.0
					]
				],
				"matrix" : 
				[
					8.740300489443445e-06,
					-1.2276567915855139e-07,
					0.0,
					1.5934898627586318e-05,
					0.0,
					0.0
				],
				"sigmas" : 
				[
					0.0035785518404845059,
					0.0048319094115564761,
					0.0
				]
			},
			"file_id" : 0,
			"nbr_active_obs" : 7,
			"number" : 8,
			"params" : 
			{
				"CHSL_E_x" : 
				{
					"rank" : 27,
					"sigma" : 0.0035785518404845059,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 766.25683970069224
				},
				"CHSL_E_y" : 
				{
					"rank" : 28,
					"sigma" : 0.0048319094115564761,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : -2085.1259773341499
				}
			},
			"shift_from_read" : 
			[
				0.00042577530257403851,
				0.00010832957923412323,
				0.0
			],
			"sigmas_init" : 
			[
				0.0030000000000000001,
				0.0040000000000000001,
				0.0
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 2,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : -1,
							"comment" : "",
							"computed_value" : 766.25683970069224,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "CHSL_E",
							"instrument_height" : 0.0,
							"line" : 12,
							"nabla" : 0.072408708371212174,
							"normalized_residual" : 0.14167547715260298,
							"number" : 16,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 2.8855501172950437,
							"obs_zen" : 0.0,
							"original_value" : 766.25641467426078,
							"rank" : 16,
							"residual" : 0.00042502643145780894,
							"residual_std" : 0.14376486365140181,
							"sigma_a_posteriori" : 0.0029563999204173046,
							"sigma_abs" : 0.0030000000000000001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00050960721203349864,
							"sigma_total" : 0.0030000000000000001,
							"standardized_residual" : 0.8340275047557022,
							"target_height" : 0.0,
							"to" : "CHSL_E",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -2,
							"comment" : "",
							"computed_value" : -2085.1259773341499,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "CHSL_E",
							"instrument_height" : 0.0,
							"line" : 12,
							"normalized_residual" : 0.027858820658366312,
							"number" : 17,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 0.40688357758550397,
							"obs_zen" : 0.0,
							"original_value" : -2085.1260887694325,
							"rank" : 17,
							"residual" : 0.00011143528263346525,
							"residual_std" : 0.027915670685461833,
							"sigma_a_posteriori" : 0.0039918540338527309,
							"sigma_abs" : 0.0040000000000000001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.0040000000000000001,
							"target_height" : 0.0,
							"to" : "CHSL_E",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						}
					],
					"params" : null,
					"type" : "simple"
				}
			]
		},
		"CHSL_O" : 
		{
			"code" : 7,
			"code_name" : "2xy ",
			"comment" : "",
			"coord_compensated_cartesian" : 
			[
				732.79189867076309,
				-2084.5574670820888,
				-0.38300702947344689
			],
			"coord_compensated_georef" : 
			[
				658620.54044282681,
				6860401.4028459499,
				0.0
			],
			"coord_compensated_latlong" : 
			[
				2.4361950065813516,
				48.842331152247311,
				0.0
			],
			"coord_init_latlong" : 
			[
				2.436195014157724,
				48.842331153668475,
				0.0
			],
			"coord_read" : 
			[
				658620.54099999997,
				6860401.4029999999,
				0.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 2,
			"ellips" : 
			{
				"axes" : 
				[
					[
						0.0048403492917722469,
						199.69937895716362,
						0.0
					],
					[
						0.0036073983300219147,
						99.699378957163574,
						0.0
					],
					[
						0.0,
						0.0,
						100.0
					]
				],
				"matrix" : 
				[
					8.8819370046509207e-06,
					-3.3568448591150942e-08,
					0.0,
					1.5990455597560564e-05,
					0.0,
					0.0
				],
				"sigmas" : 
				[
					0.0036074305211340704,
					0.0048403253003280015,
					0.0
				]
			},
			"file_id" : 0,
			"nbr_active_obs" : 3,
			"number" : 9,
			"params" : 
			{
				"CHSL_O_x" : 
				{
					"rank" : 32,
					"sigma" : 0.0036074305211340704,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 732.7918986661216
				},
				"CHSL_O_y" : 
				{
					"rank" : 33,
					"sigma" : 0.0048403253003280015,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : -2084.5574671881727
				}
			},
			"shift_from_read" : 
			[
				-0.000557173159904778,
				-0.0001540500670671463,
				0.0
			],
			"sigmas_init" : 
			[
				0.0030000000000000001,
				0.0040000000000000001,
				0.0
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 2,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : -1,
							"comment" : "",
							"computed_value" : 732.7918986661216,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "CHSL_O",
							"instrument_height" : 0.0,
							"line" : 13,
							"nabla" : 0.10739139094741101,
							"normalized_residual" : -0.18536792579955849,
							"number" : 18,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 1.3118110594342203,
							"obs_zen" : 0.0,
							"original_value" : 732.792454769899,
							"rank" : 18,
							"residual" : -0.00055610377739867545,
							"residual_std" : -0.18659585868891285,
							"sigma_a_posteriori" : 0.0029802578755287134,
							"sigma_abs" : 0.0030000000000000001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00034360296178740881,
							"sigma_total" : 0.0030000000000000001,
							"standardized_residual" : -1.6184487307846414,
							"target_height" : 0.0,
							"to" : "CHSL_O",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -2,
							"comment" : "",
							"computed_value" : -2084.5574671881727,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "CHSL_O",
							"instrument_height" : 0.0,
							"line" : 13,
							"normalized_residual" : -0.039528772390440281,
							"number" : 19,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 0.059652515246488846,
							"obs_zen" : 0.0,
							"original_value" : -2084.5573090730832,
							"rank" : 19,
							"residual" : -0.00015811508956176112,
							"residual_std" : -0.039540567621305082,
							"sigma_a_posteriori" : 0.0039988067717208545,
							"sigma_abs" : 0.0040000000000000001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.0040000000000000001,
							"target_height" : 0.0,
							"to" : "CHSL_O",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						}
					],
					"params" : null,
					"type" : "simple"
				}
			]
		},
		"GYRO" : 
		{
			"code" : 7,
			"code_name" : "2xy ",
			"comment" : " Point calibration du Gyroth\u00e9odolite",
			"coord_compensated_cartesian" : 
			[
				-0.015808788239313677,
				0.47645302885513419,
				-1.7879448560575995e-08
			],
			"coord_compensated_georef" : 
			[
				657902.98765507538,
				6862491.4765056893,
				0.0
			],
			"coord_compensated_latlong" : 
			[
				2.4262115873311298,
				48.861080732659921,
				0.0
			],
			"coord_init_latlong" : 
			[
				2.4262115918843361,
				48.861080746120699,
				0.0
			],
			"coord_read" : 
			[
				657902.98800000001,
				6862491.4780000001,
				0.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 2,
			"ellips" : 
			{
				"axes" : 
				[
					[
						0.0056811337522138629,
						17.305192227352247,
						0.0
					],
					[
						0.005358674662035305,
						117.30519222735228,
						0.0
					],
					[
						0.0,
						0.0,
						100.0
					]
				],
				"matrix" : 
				[
					1.9773819192072387e-05,
					6.2839930536243069e-07,
					0.0,
					2.1853186902815631e-05,
					0.0,
					0.0
				],
				"sigmas" : 
				[
					0.0053825665783511717,
					0.0056585026176277173,
					0.0
				]
			},
			"file_id" : 0,
			"nbr_active_obs" : 24,
			"number" : 4,
			"params" : 
			{
				"GYRO_x" : 
				{
					"rank" : 12,
					"sigma" : 0.0053825665783511717,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : -0.015808788254326887
				},
				"GYRO_y" : 
				{
					"rank" : 13,
					"sigma" : 0.0056585026176277173,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 0.47645302955293112
				}
			},
			"shift_from_read" : 
			[
				-0.00034492462873458862,
				-0.0014943107962608337,
				0.0
			],
			"sigmas_init" : 
			[
				0.0050000000000000001,
				0.0050000000000000001,
				0.0
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 2,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : -1,
							"comment" : " Point calibration du Gyroth\u00e9odolite",
							"computed_value" : -0.015808788254326887,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 5,
							"nabla" : 0.044836494466975997,
							"normalized_residual" : -0.066818374840548964,
							"number" : 8,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 20.904723231710442,
							"obs_zen" : 0.0,
							"original_value" : -0.015474696380124142,
							"rank" : 8,
							"residual" : -0.00033409187420274482,
							"residual_std" : -0.075131253282313779,
							"sigma_a_posteriori" : 0.004446776269621892,
							"sigma_abs" : 0.0050000000000000001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.0022860841646640245,
							"sigma_total" : 0.0050000000000000001,
							"standardized_residual" : -0.14614154604051718,
							"target_height" : 0.0,
							"to" : "GYRO",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -2,
							"comment" : " Point calibration du Gyroth\u00e9odolite",
							"computed_value" : 0.47645302955293112,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 5,
							"nabla" : 0.05778144398508097,
							"normalized_residual" : -0.29938646109288758,
							"number" : 9,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 12.587252388737479,
							"obs_zen" : 0.0,
							"original_value" : 0.47794996185839556,
							"rank" : 9,
							"residual" : -0.0014969323054644379,
							"residual_std" : -0.32021728499477614,
							"sigma_a_posteriori" : 0.0046747392336702193,
							"sigma_abs" : 0.0050000000000000001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.0017739258995753946,
							"sigma_total" : 0.0050000000000000001,
							"standardized_residual" : -0.84385278202586833,
							"target_height" : 0.0,
							"to" : "GYRO",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						}
					],
					"params" : null,
					"type" : "simple"
				},
				{
					"nbr_active_obs" : 7,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : 7,
							"comment" : "",
							"computed_value" : -0.0015728379158036626,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 21,
							"nabla" : 0.0047097426042519031,
							"normalized_residual" : -1.5728379157753909,
							"number" : 34,
							"obs_azim" : 2.7894921605137997,
							"obs_length" : 2221.9161144107175,
							"obs_redondancy" : 75.783274699277868,
							"obs_zen" : 1.5709495388416381,
							"original_value" : 0.0,
							"rank" : 34,
							"residual" : -0.001572837915775391,
							"residual_std" : -3.196143443232486,
							"sigma_a_posteriori" : 0.00049210492073055044,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00087053589644125453,
							"sigma_total" : 0.001,
							"standardized_residual" : -1.8067467662219823,
							"target_height" : 0.0,
							"to" : "CHSL_E",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : 27.580412259681598,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 22,
							"nabla" : 0.0047486703647493635,
							"normalized_residual" : 1.1122596815952146,
							"number" : 35,
							"obs_azim" : -3.0604363378956108,
							"obs_length" : 1724.4218885431255,
							"obs_redondancy" : 74.545883529579854,
							"obs_zen" : 1.5709152341670296,
							"original_value" : 27.5793,
							"rank" : 35,
							"residual" : 0.0011122596815952145,
							"residual_std" : 2.2045866908393759,
							"sigma_a_posteriori" : 0.00050452072772503762,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.0008633995803194476,
							"sigma_total" : 0.001,
							"standardized_residual" : 1.288232826316283,
							"target_height" : 0.0,
							"to" : "IGNF",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : 104.9585162346791,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 23,
							"nabla" : 0.0048572702969796443,
							"normalized_residual" : 0.21623467913011274,
							"number" : 36,
							"obs_azim" : -1.844983922912814,
							"obs_length" : 6104.4200383776315,
							"obs_redondancy" : 71.249721313269887,
							"obs_zen" : 1.5712172566013933,
							"original_value" : 104.95829999999999,
							"rank" : 36,
							"residual" : 0.00021623467913011276,
							"residual_std" : 0.40327780142209874,
							"sigma_a_posteriori" : 0.00053619286349904094,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00084409550000737405,
							"sigma_total" : 0.001,
							"standardized_residual" : 0.25617324002820024,
							"target_height" : 0.0,
							"to" : "PTHN",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : 120.40468654296068,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 24,
							"nabla" : 0.0047863654260053611,
							"normalized_residual" : -0.2134570393774248,
							"number" : 37,
							"obs_azim" : -1.6023560470798432,
							"obs_length" : 9669.5937657680643,
							"obs_redondancy" : 73.376333667957937,
							"obs_zen" : 1.5714630929154245,
							"original_value" : 120.4049,
							"rank" : 37,
							"residual" : -0.00021345703937742481,
							"residual_std" : -0.41369145521952599,
							"sigma_a_posteriori" : 0.00051598126256717947,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00085659986964718802,
							"sigma_total" : 0.001,
							"standardized_residual" : -0.24919107151550515,
							"target_height" : 0.0,
							"to" : "TFLE",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : -152.85473199088921,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 25,
							"nabla" : 0.0089650205774225063,
							"normalized_residual" : 0.068009110813677068,
							"number" : 38,
							"obs_azim" : 0.38848035114893609,
							"obs_length" : 346.47844313485479,
							"obs_redondancy" : 20.915349781046821,
							"obs_zen" : 1.5708202181883486,
							"original_value" : -152.85480000000001,
							"rank" : 38,
							"residual" : 6.8009110813677074e-05,
							"residual_std" : 0.076475266243149723,
							"sigma_a_posteriori" : 0.00088929550892238949,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00045733302724652224,
							"sigma_total" : 0.001,
							"standardized_residual" : 0.14870806777971279,
							"target_height" : 0.0,
							"to" : "BAT4",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : 97.303620732866975,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 26,
							"nabla" : 0.0058909502026485575,
							"normalized_residual" : 0.42073286699285278,
							"number" : 39,
							"obs_azim" : -1.965226740275267,
							"obs_length" : 7131.547739245043,
							"obs_redondancy" : 48.439205394983794,
							"obs_zen" : 1.5712880821185522,
							"original_value" : 97.303200000000004,
							"rank" : 39,
							"residual" : 0.00042073286699285283,
							"residual_std" : 0.58593121987758123,
							"sigma_a_posteriori" : 0.00071805845587261357,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00069598279716515837,
							"sigma_total" : 0.001,
							"standardized_residual" : 0.60451618733474521,
							"target_height" : 0.0,
							"to" : "OBSV",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : 145.32103387289516,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 27,
							"nabla" : 0.19175469976218587,
							"normalized_residual" : -0.9929661664367373,
							"number" : 40,
							"obs_azim" : -1.2109709784497735,
							"obs_length" : 20.475451027087075,
							"obs_redondancy" : 47.083132119444649,
							"obs_zen" : 1.5707977386925374,
							"original_value" : 145.35290000000001,
							"rank" : 40,
							"residual" : -0.031866127104840582,
							"residual_std" : -1.3650148799319484,
							"sigma_a_posteriori" : 0.02334489357832439,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.01,
							"sigma_residual" : 0.022020516740066932,
							"sigma_total" : 0.032091855877821387,
							"standardized_residual" : -1.4471107776893943,
							"target_height" : 0.0,
							"to" : "S1",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						}
					],
					"params" : 
					{
						"GYRO_G0_1" : 
						{
							"rank" : 14,
							"sigma" : 9.1426830033980267e-06,
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"value" : 2.7895168665940075
						}
					},
					"type" : "hz_unknown"
				},
				{
					"nbr_active_obs" : 15,
					"num" : 2,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : 7,
							"comment" : "",
							"computed_value" : -80.339632856812514,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 52,
							"nabla" : 0.0043451686511517635,
							"normalized_residual" : 2.3671431874053694,
							"number" : 48,
							"obs_azim" : -1.844983922912814,
							"obs_length" : 6104.4200383776315,
							"obs_redondancy" : 89.033703360496048,
							"obs_zen" : 1.5712172566013933,
							"original_value" : 319.65800000000002,
							"probable_error" : -0.0026587046231479833,
							"rank" : 48,
							"residual" : 0.0023671431874053698,
							"residual_std" : 7.1481644335671195,
							"sigma_a_posteriori" : 0.00033115399196603312,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00094357672375115331,
							"sigma_total" : 0.001,
							"standardized_residual" : 2.5086917977320193,
							"target_height" : 0.0,
							"to" : "PTHN",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : -80.339632856812514,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 53,
							"nabla" : 0.0043451686511517635,
							"normalized_residual" : -1.0328568125809612,
							"number" : 49,
							"obs_azim" : -1.844983922912814,
							"obs_length" : 6104.4200383776315,
							"obs_redondancy" : 89.033703360496048,
							"obs_zen" : 1.5712172566013933,
							"original_value" : 319.66140000000001,
							"rank" : 49,
							"residual" : -0.0010328568125809613,
							"residual_std" : -3.1189622883570816,
							"sigma_a_posteriori" : 0.00033115399196603312,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00094357672375115331,
							"sigma_total" : 0.001,
							"standardized_residual" : -1.0946187910134941,
							"target_height" : 0.0,
							"to" : "PTHN",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : -80.339632856812514,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 54,
							"nabla" : 0.0043451686511517635,
							"normalized_residual" : -2.4328568125753329,
							"number" : 50,
							"obs_azim" : -1.844983922912814,
							"obs_length" : 6104.4200383776315,
							"obs_redondancy" : 89.033703360496048,
							"obs_zen" : 1.5712172566013933,
							"original_value" : 319.6628,
							"probable_error" : 0.0027325122068939827,
							"rank" : 50,
							"residual" : -0.0024328568125753327,
							"residual_std" : -7.3466027032670462,
							"sigma_a_posteriori" : 0.00033115399196603312,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00094357672375115331,
							"sigma_total" : 0.001,
							"standardized_residual" : -2.5783349157910584,
							"target_height" : 0.0,
							"to" : "PTHN",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : -80.339632856812514,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 55,
							"nabla" : 0.0043451686511517635,
							"normalized_residual" : 0.46714318752609463,
							"number" : 51,
							"obs_azim" : -1.844983922912814,
							"obs_length" : 6104.4200383776315,
							"obs_redondancy" : 89.033703360496048,
							"obs_zen" : 1.5712172566013933,
							"original_value" : 319.65989999999999,
							"rank" : 51,
							"residual" : 0.00046714318752609464,
							"residual_std" : 1.4106524422450872,
							"sigma_a_posteriori" : 0.00033115399196603312,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00094357672375115331,
							"sigma_total" : 0.001,
							"standardized_residual" : 0.4950770570823162,
							"target_height" : 0.0,
							"to" : "PTHN",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : -80.339632856812514,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 56,
							"nabla" : 0.0043451686511517635,
							"normalized_residual" : 0.7671431874118021,
							"number" : 52,
							"obs_azim" : -1.844983922912814,
							"obs_length" : 6104.4200383776315,
							"obs_redondancy" : 89.033703360496048,
							"obs_zen" : 1.5712172566013933,
							"original_value" : 319.65960000000001,
							"rank" : 52,
							"residual" : 0.00076714318741180219,
							"residual_std" : 2.3165753879557309,
							"sigma_a_posteriori" : 0.00033115399196603312,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00094357672375115331,
							"sigma_total" : 0.001,
							"standardized_residual" : 0.81301622655765993,
							"target_height" : 0.0,
							"to" : "PTHN",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : -80.339632856812514,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 57,
							"nabla" : 0.0043451686511517635,
							"normalized_residual" : 0.7671431874118021,
							"number" : 53,
							"obs_azim" : -1.844983922912814,
							"obs_length" : 6104.4200383776315,
							"obs_redondancy" : 89.033703360496048,
							"obs_zen" : 1.5712172566013933,
							"original_value" : 319.65960000000001,
							"rank" : 53,
							"residual" : 0.00076714318741180219,
							"residual_std" : 2.3165753879557309,
							"sigma_a_posteriori" : 0.00033115399196603312,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00094357672375115331,
							"sigma_total" : 0.001,
							"standardized_residual" : 0.81301622655765993,
							"target_height" : 0.0,
							"to" : "PTHN",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : -64.893462548530948,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 58,
							"nabla" : 0.0043470418630937617,
							"normalized_residual" : -0.76254853097822661,
							"number" : 54,
							"obs_azim" : -1.6023560470798432,
							"obs_length" : 9669.5937657680643,
							"obs_redondancy" : 88.956987714446015,
							"obs_zen" : 1.5714630929154245,
							"original_value" : 335.10730000000001,
							"rank" : 54,
							"residual" : -0.00076254853097822671,
							"residual_std" : -2.2946883517809455,
							"sigma_a_posteriori" : 0.0003323102809958486,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00094317012099857152,
							"sigma_total" : 0.001,
							"standardized_residual" : -0.80849521629341514,
							"target_height" : 0.0,
							"to" : "TFLE",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : -64.893462548530948,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 59,
							"nabla" : 0.0043470418630937617,
							"normalized_residual" : -2.162548530972598,
							"number" : 55,
							"obs_azim" : -1.6023560470798432,
							"obs_length" : 9669.5937657680643,
							"obs_redondancy" : 88.956987714446015,
							"obs_zen" : 1.5714630929154245,
							"original_value" : 335.1087,
							"rank" : 55,
							"residual" : -0.0021625485309725982,
							"residual_std" : -6.5076184958587371,
							"sigma_a_posteriori" : 0.0003323102809958486,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00094317012099857152,
							"sigma_total" : 0.001,
							"standardized_residual" : -2.2928509744170249,
							"target_height" : 0.0,
							"to" : "TFLE",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : -64.893462548530948,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 60,
							"nabla" : 0.0043470418630937617,
							"normalized_residual" : 2.0374514690105165,
							"number" : 56,
							"obs_azim" : -1.6023560470798432,
							"obs_length" : 9669.5937657680643,
							"obs_redondancy" : 88.956987714446015,
							"obs_zen" : 1.5714630929154245,
							"original_value" : 335.10449999999997,
							"rank" : 56,
							"residual" : 0.0020374514690105166,
							"residual_std" : 6.1311719363746366,
							"sigma_a_posteriori" : 0.0003323102809958486,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00094317012099857152,
							"sigma_total" : 0.001,
							"standardized_residual" : 2.1602162999538046,
							"target_height" : 0.0,
							"to" : "TFLE",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : -64.893462548530948,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 61,
							"nabla" : 0.0043470418630937617,
							"normalized_residual" : 0.83745146901534084,
							"number" : 57,
							"obs_azim" : -1.6023560470798432,
							"obs_length" : 9669.5937657680643,
							"obs_redondancy" : 88.956987714446015,
							"obs_zen" : 1.5714630929154245,
							"original_value" : 335.10570000000001,
							"rank" : 57,
							"residual" : 0.0008374514690153408,
							"residual_std" : 2.5200889557365298,
							"sigma_a_posteriori" : 0.0003323102809958486,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00094317012099857152,
							"sigma_total" : 0.001,
							"standardized_residual" : 0.88791136441928187,
							"target_height" : 0.0,
							"to" : "TFLE",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : -64.893462548530948,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 62,
							"nabla" : 0.0043470418630937617,
							"normalized_residual" : 0.63745146901614491,
							"number" : 58,
							"obs_azim" : -1.6023560470798432,
							"obs_length" : 9669.5937657680643,
							"obs_redondancy" : 88.956987714446015,
							"obs_zen" : 1.5714630929154245,
							"original_value" : 335.10590000000002,
							"rank" : 58,
							"residual" : 0.00063745146901614486,
							"residual_std" : 1.9182417922968453,
							"sigma_a_posteriori" : 0.0003323102809958486,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00094317012099857152,
							"sigma_total" : 0.001,
							"standardized_residual" : 0.67586054183019473,
							"target_height" : 0.0,
							"to" : "TFLE",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : -157.00507252911743,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 63,
							"nabla" : 0.0043911779646706815,
							"normalized_residual" : -0.17252911745156357,
							"number" : 59,
							"obs_azim" : -3.0492418332065374,
							"obs_length" : 7708.7839154984204,
							"obs_redondancy" : 87.177746098993794,
							"obs_zen" : 1.5713278853991284,
							"original_value" : 242.99510000000001,
							"rank" : 59,
							"residual" : -0.0001725291174515636,
							"residual_std" : -0.48181488697578018,
							"sigma_a_posteriori" : 0.00035808174906026987,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.0009336902382428221,
							"sigma_total" : 0.001,
							"standardized_residual" : -0.18478196556521612,
							"target_height" : 0.0,
							"to" : "VITRY",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : -157.00507252911743,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 64,
							"nabla" : 0.0043911779646706815,
							"normalized_residual" : -1.2725291174471411,
							"number" : 60,
							"obs_azim" : -3.0492418332065374,
							"obs_length" : 7708.7839154984204,
							"obs_redondancy" : 87.177746098993794,
							"obs_zen" : 1.5713278853991284,
							"original_value" : 242.99619999999999,
							"rank" : 60,
							"residual" : -0.0012725291174471413,
							"residual_std" : -3.5537391134474099,
							"sigma_a_posteriori" : 0.00035808174906026987,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.0009336902382428221,
							"sigma_total" : 0.001,
							"standardized_residual" : -1.3629028829111507,
							"target_height" : 0.0,
							"to" : "VITRY",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : -157.00507252911743,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 65,
							"nabla" : 0.0043911779646706815,
							"normalized_residual" : -0.77252911744915143,
							"number" : 61,
							"obs_azim" : -3.0492418332065374,
							"obs_length" : 7708.7839154984204,
							"obs_redondancy" : 87.177746098993794,
							"obs_zen" : 1.5713278853991284,
							"original_value" : 242.9957,
							"rank" : 61,
							"residual" : -0.00077252911744915141,
							"residual_std" : -2.1574099195966689,
							"sigma_a_posteriori" : 0.00035808174906026987,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.0009336902382428221,
							"sigma_total" : 0.001,
							"standardized_residual" : -0.8273933750266349,
							"target_height" : 0.0,
							"to" : "VITRY",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : -157.00507252911743,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "GYRO",
							"instrument_height" : 0.0,
							"line" : 66,
							"nabla" : 0.0043911779646706815,
							"normalized_residual" : 0.72747088254481806,
							"number" : 62,
							"obs_azim" : -3.0492418332065374,
							"obs_length" : 7708.7839154984204,
							"obs_redondancy" : 87.177746098993794,
							"obs_zen" : 1.5713278853991284,
							"original_value" : 242.99420000000001,
							"rank" : 62,
							"residual" : 0.00072747088254481818,
							"residual_std" : 2.0315776619555534,
							"sigma_a_posteriori" : 0.00035808174906026987,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.0009336902382428221,
							"sigma_total" : 0.001,
							"standardized_residual" : 0.77913514862691213,
							"target_height" : 0.0,
							"to" : "VITRY",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						}
					],
					"params" : 
					{
						"GYRO_G0_2" : 
						{
							"rank" : 15,
							"sigma" : 6.844526141775513e-06,
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"value" : -0.58301192103749711
						}
					},
					"type" : "hz_unknown"
				}
			]
		},
		"IGNF" : 
		{
			"code" : 7,
			"code_name" : "2xy ",
			"comment" : "",
			"coord_compensated_cartesian" : 
			[
				-139.80996290907203,
				-1718.2697359263559,
				-0.23321454451115642
			],
			"coord_compensated_georef" : 
			[
				657750.72536807403,
				6860773.9799673688,
				0.0
			],
			"coord_compensated_latlong" : 
			[
				2.4243069742873353,
				48.845625324545061,
				0.0
			],
			"coord_init_latlong" : 
			[
				2.4243069692688559,
				48.845625324814378,
				0.0
			],
			"coord_read" : 
			[
				657750.72499999998,
				6860773.9800000004,
				0.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 2,
			"ellips" : 
			{
				"axes" : 
				[
					[
						0.0036313272258301733,
						5.1665715222687449,
						0.0
					],
					[
						0.0036146865491807111,
						105.16657152226875,
						0.0
					],
					[
						0.0,
						0.0,
						100.0
					]
				],
				"matrix" : 
				[
					8.9182442484745697e-06,
					6.649600855581063e-09,
					0.0,
					8.9994591549742546e-06,
					0.0,
					0.0
				],
				"sigmas" : 
				[
					0.0036147961601147431,
					0.0036312181138983012,
					0.0
				]
			},
			"file_id" : 0,
			"nbr_active_obs" : 3,
			"number" : 7,
			"params" : 
			{
				"IGNF_x" : 
				{
					"rank" : 2,
					"sigma" : 0.0036147961601147431,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : -139.80996290907277
				},
				"IGNF_y" : 
				{
					"rank" : 3,
					"sigma" : 0.0036312181138983012,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : -1718.2697359866613
				}
			},
			"shift_from_read" : 
			[
				0.00036807404831051826,
				-3.2631680369377136e-05,
				0.0
			],
			"sigmas_init" : 
			[
				0.0030000000000000001,
				0.0030000000000000001,
				0.0
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 2,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : -1,
							"comment" : "",
							"computed_value" : -139.80996290907277,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "IGNF",
							"instrument_height" : 0.0,
							"line" : 11,
							"normalized_residual" : 0.12278131043785834,
							"number" : 14,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 0.90839723917144344,
							"obs_zen" : 0.0,
							"original_value" : -139.81033125300408,
							"rank" : 14,
							"residual" : 0.00036834393131357501,
							"residual_std" : 0.12334280984794141,
							"sigma_a_posteriori" : 0.0029863429556021477,
							"sigma_abs" : 0.0030000000000000001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.0030000000000000001,
							"target_height" : 0.0,
							"to" : "IGNF",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -2,
							"comment" : "",
							"computed_value" : -1718.2697359866613,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "IGNF",
							"instrument_height" : 0.0,
							"line" : 11,
							"normalized_residual" : -0.009986413109193867,
							"number" : 15,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 0.006009389174954638,
							"obs_zen" : 0.0,
							"original_value" : -1718.269706027422,
							"rank" : 15,
							"residual" : -2.9959239327581599e-05,
							"residual_std" : -0.009986713183932603,
							"sigma_a_posteriori" : 0.0029999098578081065,
							"sigma_abs" : 0.0030000000000000001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.0030000000000000001,
							"target_height" : 0.0,
							"to" : "IGNF",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						}
					],
					"params" : null,
					"type" : "simple"
				}
			]
		},
		"OBSV" : 
		{
			"code" : 7,
			"code_name" : "2xy ",
			"comment" : "",
			"coord_compensated_cartesian" : 
			[
				-6583.9722525469469,
				-2740.0519706663295,
				-3.9809336821003853
			],
			"coord_compensated_georef" : 
			[
				651300.09418030549,
				6859799.0252267327,
				0.0
			],
			"coord_compensated_latlong" : 
			[
				2.3365254860486186,
				48.836402303159744,
				0.0
			],
			"coord_init_latlong" : 
			[
				2.3365252888885388,
				48.83640261480609,
				0.0
			],
			"coord_read" : 
			[
				651300.07999999996,
				6859799.0599999996,
				0.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 2,
			"ellips" : 
			{
				"axes" : 
				[
					[
						0.12104424086100582,
						74.889779993041387,
						0.0
					],
					[
						0.094847871172670711,
						174.88977999304134,
						0.0
					],
					[
						0.0,
						0.0,
						100.0
					]
				],
				"matrix" : 
				[
					0.0094299793193593374,
					0.0013694407613713245,
					0.0,
					0.0067100000708790594,
					0.0,
					0.0
				],
				"sigmas" : 
				[
					0.11754373898658182,
					0.099152893738201422,
					0.0
				]
			},
			"file_id" : 0,
			"nbr_active_obs" : 3,
			"number" : 11,
			"params" : 
			{
				"OBSV_x" : 
				{
					"rank" : 0,
					"sigma" : 0.11754373898658182,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : -6583.972249153584
				},
				"OBSV_y" : 
				{
					"rank" : 1,
					"sigma" : 0.099152893738201422,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : -2740.0519709143919
				}
			},
			"shift_from_read" : 
			[
				0.014180305530317128,
				-0.03477326687425375,
				0.0
			],
			"sigmas_init" : 
			[
				0.10000000000000001,
				0.10000000000000001,
				0.0
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 2,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : -1,
							"comment" : "",
							"computed_value" : -6583.972249153584,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "OBSV",
							"instrument_height" : 0.0,
							"line" : 15,
							"nabla" : 1.7172698714354171,
							"normalized_residual" : 0.14432887977818609,
							"number" : 22,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 5.700206806406638,
							"obs_zen" : 0.0,
							"original_value" : -6583.9866820415618,
							"rank" : 22,
							"residual" : 0.014432887977818609,
							"residual_std" : 0.14862705438580792,
							"sigma_a_posteriori" : 0.097108080607945998,
							"sigma_abs" : 0.10000000000000001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.02387510587705664,
							"sigma_total" : 0.10000000000000001,
							"standardized_residual" : 0.60451618736854451,
							"target_height" : 0.0,
							"to" : "OBSV",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -2,
							"comment" : "",
							"computed_value" : -2740.0519709143919,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "OBSV",
							"instrument_height" : 0.0,
							"line" : 15,
							"nabla" : 0.71480225254804042,
							"normalized_residual" : -0.3467415439990873,
							"number" : 23,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 32.899999291209411,
							"obs_zen" : 0.0,
							"original_value" : -2740.017296759992,
							"rank" : 23,
							"residual" : -0.03467415439990873,
							"residual_std" : -0.42329644033547797,
							"sigma_a_posteriori" : 0.081914590097729598,
							"sigma_abs" : 0.10000000000000001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.057358520980940068,
							"sigma_total" : 0.10000000000000001,
							"standardized_residual" : -0.60451618707934895,
							"target_height" : 0.0,
							"to" : "OBSV",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						}
					],
					"params" : null,
					"type" : "simple"
				}
			]
		},
		"PC1" : 
		{
			"code" : 7,
			"code_name" : "2xy ",
			"comment" : " Point contr\u00f4le 1 : pont",
			"coord_compensated_cartesian" : 
			[
				-101.73295503280552,
				262.402041950262,
				-0.0062129720792825083
			],
			"coord_compensated_georef" : 
			[
				657803.18670749187,
				6862754.1071444033,
				0.0
			],
			"coord_compensated_latlong" : 
			[
				2.4248252593514485,
				48.863436020552605,
				0.0
			],
			"coord_init_latlong" : 
			[
				2.4248253172781542,
				48.863436073492672,
				0.0
			],
			"coord_read" : 
			[
				657803.19099999999,
				6862754.1129999999,
				0.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 2,
			"ellips" : 
			{
				"axes" : 
				[
					[
						0.011603597700826279,
						85.584335741055497,
						0.0
					],
					[
						0.0081105918521732247,
						185.5843357410557,
						0.0
					],
					[
						0.0,
						0.0,
						100.0
					]
				],
				"matrix" : 
				[
					8.9527105380801767e-05,
					1.0282433909575416e-05,
					0.0,
					4.7265940477938592e-05,
					0.0,
					0.0
				],
				"sigmas" : 
				[
					0.011453056483376533,
					0.0083218193313569604,
					0.0
				]
			},
			"file_id" : 0,
			"nbr_active_obs" : 6,
			"number" : 2,
			"params" : 
			{
				"PC1_x" : 
				{
					"rank" : 19,
					"sigma" : 0.011453056483376533,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : -101.73295503276339
				},
				"PC1_y" : 
				{
					"rank" : 20,
					"sigma" : 0.0083218193313569604,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 262.40204195155695
				}
			},
			"shift_from_read" : 
			[
				-0.0042925081215798855,
				-0.005855596624314785,
				0.0
			],
			"sigmas_init" : 
			[
				0.01,
				0.01,
				0.0
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 2,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : -1,
							"comment" : " Point contr\u00f4le 1 : pont",
							"computed_value" : -101.73295503276339,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "PC1",
							"instrument_height" : 0.0,
							"line" : 3,
							"nabla" : 0.12669237859979668,
							"normalized_residual" : -0.42502842191396439,
							"number" : 4,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 10.472894619198236,
							"obs_zen" : 0.0,
							"original_value" : -101.72870474854425,
							"rank" : 4,
							"residual" : -0.0042502842191396439,
							"residual_std" : -0.44920098621359184,
							"sigma_a_posteriori" : 0.0094618764196538613,
							"sigma_abs" : 0.01,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.0032361851954420405,
							"sigma_total" : 0.01,
							"standardized_residual" : -1.3133624815804414,
							"target_height" : 0.0,
							"to" : "PC1",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -2,
							"comment" : " Point contr\u00f4le 1 : pont",
							"computed_value" : 262.40204195155695,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "PC1",
							"instrument_height" : 0.0,
							"line" : 3,
							"nabla" : 0.056459659440331995,
							"normalized_residual" : -0.58872313631468387,
							"number" : 5,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 52.734059522061415,
							"obs_zen" : 0.0,
							"original_value" : 262.4079291829201,
							"rank" : 5,
							"residual" : -0.0058872313631468387,
							"residual_std" : -0.85632170412550168,
							"sigma_a_posteriori" : 0.0068750229438117941,
							"sigma_abs" : 0.01,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.0072618220524921584,
							"sigma_total" : 0.01,
							"standardized_residual" : -0.81070994587734646,
							"target_height" : 0.0,
							"to" : "PC1",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						}
					],
					"params" : null,
					"type" : "simple"
				},
				{
					"nbr_active_obs" : 4,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : 7,
							"comment" : "",
							"computed_value" : -0.00022641449425992669,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "PC1",
							"instrument_height" : 0.0,
							"line" : 5,
							"nabla" : 0.0032178726523084504,
							"normalized_residual" : -0.3773574904096515,
							"number" : 26,
							"obs_azim" : -1.8909714419220616,
							"obs_length" : 6083.8548616953794,
							"obs_redondancy" : 58.44300100170927,
							"obs_zen" : 1.5712158385311117,
							"original_value" : 0.0,
							"rank" : 26,
							"residual" : -0.00022641449424579089,
							"residual_std" : -0.5853705726455497,
							"sigma_a_posteriori" : 0.00038678830953616812,
							"sigma_abs" : 0.00059999999999999995,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00045868813327374551,
							"sigma_total" : 0.00059999999999999995,
							"standardized_residual" : -0.49361314981014892,
							"target_height" : 0.0,
							"to" : "PTHN",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : 16.612315338141173,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "PC1",
							"instrument_height" : 0.0,
							"line" : 6,
							"nabla" : 0.0027219702950230539,
							"normalized_residual" : -0.36809503845762681,
							"number" : 27,
							"obs_azim" : -1.6300222462843956,
							"obs_length" : 9579.8582987231966,
							"obs_redondancy" : 12.002082912867074,
							"obs_zen" : 1.5714569052117453,
							"original_value" : 16.612400000000001,
							"rank" : 27,
							"residual" : -8.4661858845254173e-05,
							"residual_std" : -0.39239527335101632,
							"sigma_a_posteriori" : 0.00021575657148530455,
							"sigma_abs" : 0.00023000000000000001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 7.9681251627385227e-05,
							"sigma_total" : 0.00023000000000000001,
							"standardized_residual" : -1.0625066388409639,
							"target_height" : 0.0,
							"to" : "TFLE",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : 204.65942074766014,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "PC1",
							"instrument_height" : 0.0,
							"line" : 7,
							"nabla" : 0.014970520696000789,
							"normalized_residual" : 0.043224292008797051,
							"number" : 28,
							"obs_azim" : 1.3238147781324556,
							"obs_length" : 240.24745732220671,
							"obs_redondancy" : 1.7281298674479029,
							"obs_zen" : 1.5708128930392971,
							"original_value" : -195.34059999999999,
							"rank" : 28,
							"residual" : 2.0747660164222584e-05,
							"residual_std" : 0.043602689483287771,
							"sigma_a_posteriori" : 0.00047583441320001225,
							"sigma_abs" : 0.00048000000000000001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 6.310000962440475e-05,
							"sigma_total" : 0.00048000000000000001,
							"standardized_residual" : 0.3288059746380475,
							"target_height" : 0.0,
							"to" : "BAT4",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : 297.83643565491593,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "PC1",
							"instrument_height" : 0.0,
							"line" : 8,
							"nabla" : 0.0037583076902328676,
							"normalized_residual" : 1.6258617314958563,
							"number" : 29,
							"obs_azim" : 2.7874359057127629,
							"obs_length" : 2502.8571682737852,
							"obs_redondancy" : 68.740111577793712,
							"obs_zen" : 1.5709689111097276,
							"original_value" : -102.1648,
							"rank" : 29,
							"residual" : 0.001235654915936851,
							"residual_std" : 2.9079698355665018,
							"sigma_a_posteriori" : 0.00042492012840846162,
							"sigma_abs" : 0.00076000000000000004,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00063011339017143289,
							"sigma_total" : 0.00076000000000000004,
							"standardized_residual" : 1.9610040592863298,
							"target_height" : 0.0,
							"to" : "CHSL_E",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						}
					],
					"params" : 
					{
						"PC1_G0_1" : 
						{
							"rank" : 21,
							"sigma" : 7.266558209469155e-06,
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"value" : -1.8909678854115024
						}
					},
					"type" : "hz_unknown"
				}
			]
		},
		"PC2" : 
		{
			"code" : 7,
			"code_name" : "2xy ",
			"comment" : " Point contr\u00f4le 2 : Rue D\u00e9sir\u00e9 Preaux",
			"coord_compensated_cartesian" : 
			[
				367.69545980647763,
				198.24113141339484,
				-0.013662477649518223
			],
			"coord_compensated_georef" : 
			[
				658272.08830398333,
				6862686.5433402956,
				0.0
			],
			"coord_compensated_latlong" : 
			[
				2.4312231569087439,
				48.86285897014826,
				0.0
			],
			"coord_init_latlong" : 
			[
				2.43122315279882,
				48.862858967068306,
				0.0
			],
			"coord_read" : 
			[
				658272.08799999999,
				6862686.5429999996,
				0.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 2,
			"ellips" : 
			{
				"axes" : 
				[
					[
						0.01210430830247226,
						135.99225472365777,
						0.0
					],
					[
						0.0083727615930538138,
						35.992254723657751,
						0.0
					],
					[
						0.0,
						0.0,
						100.0
					]
				],
				"matrix" : 
				[
					8.5030535858450187e-05,
					-2.3591430259472282e-05,
					0.0,
					6.281394243998541e-05,
					0.0,
					0.0
				],
				"sigmas" : 
				[
					0.011161731959541506,
					0.0095933912585052915,
					0.0
				]
			},
			"file_id" : 0,
			"nbr_active_obs" : 5,
			"number" : 3,
			"params" : 
			{
				"PC2_x" : 
				{
					"rank" : 29,
					"sigma" : 0.011161731959541506,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 367.69545980590351
				},
				"PC2_y" : 
				{
					"rank" : 30,
					"sigma" : 0.0095933912585052915,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 198.24113141317437
				}
			},
			"shift_from_read" : 
			[
				0.00030398333910852671,
				0.00034029595553874969,
				0.0
			],
			"sigmas_init" : 
			[
				0.01,
				0.01,
				0.0
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 2,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : -1,
							"comment" : " Point contr\u00f4le 2 : Rue D\u00e9sir\u00e9 Preaux",
							"computed_value" : 367.69545980590351,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "PC2",
							"instrument_height" : 0.0,
							"line" : 4,
							"nabla" : 0.10596946202982523,
							"normalized_residual" : 0.030153274337862968,
							"number" : 6,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 14.969464141549803,
							"obs_zen" : 0.0,
							"original_value" : 367.69515827316013,
							"rank" : 6,
							"residual" : 0.00030153274337862968,
							"residual_std" : 0.032699944909357938,
							"sigma_a_posteriori" : 0.0092212003480268336,
							"sigma_abs" : 0.01,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.0038690391754994942,
							"sigma_total" : 0.01,
							"standardized_residual" : 0.077934786829782277,
							"target_height" : 0.0,
							"to" : "PC2",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -2,
							"comment" : " Point contr\u00f4le 2 : Rue D\u00e9sir\u00e9 Preaux",
							"computed_value" : 198.24113141317437,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "PC2",
							"instrument_height" : 0.0,
							"line" : 4,
							"nabla" : 0.067234749032168931,
							"normalized_residual" : 0.034253190020194779,
							"number" : 7,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 37.186057560014596,
							"obs_zen" : 0.0,
							"original_value" : 198.24078888127417,
							"rank" : 7,
							"residual" : 0.00034253190020194779,
							"residual_std" : 0.043218829205849074,
							"sigma_a_posteriori" : 0.0079255247422480111,
							"sigma_abs" : 0.01,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.0060980371891301722,
							"sigma_total" : 0.01,
							"standardized_residual" : 0.056170844745341203,
							"target_height" : 0.0,
							"to" : "PC2",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						}
					],
					"params" : null,
					"type" : "simple"
				},
				{
					"nbr_active_obs" : 3,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : 7,
							"comment" : "",
							"computed_value" : 0.00081093414670083261,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "PC2",
							"instrument_height" : 0.0,
							"line" : 44,
							"nabla" : 0.0029467263313158638,
							"normalized_residual" : 1.351556911215174,
							"number" : 45,
							"obs_azim" : 2.9687837855004178,
							"obs_length" : 2317.8905210937251,
							"obs_redondancy" : 69.693232192970015,
							"obs_zen" : 1.570956156749385,
							"original_value" : 0.0,
							"rank" : 45,
							"residual" : 0.00081093414672910426,
							"residual_std" : 2.4550736596764349,
							"sigma_a_posteriori" : 0.00033030949744944956,
							"sigma_abs" : 0.00059999999999999995,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00050089483516471993,
							"sigma_total" : 0.00059999999999999995,
							"standardized_residual" : 1.6189708693291429,
							"target_height" : 0.0,
							"to" : "CHSL_E",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : 0.90597187672784818,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "PC2",
							"instrument_height" : 0.0,
							"line" : 45,
							"nabla" : 0.0029202024599085468,
							"normalized_residual" : -0.86348229514547947,
							"number" : 46,
							"obs_azim" : 2.9830020203380645,
							"obs_length" : 2311.809852255491,
							"obs_redondancy" : 28.464855385606946,
							"obs_zen" : 1.5709557374573193,
							"original_value" : 0.90629999999999999,
							"rank" : 46,
							"residual" : -0.00032812327215528224,
							"residual_std" : -1.0209246913751129,
							"sigma_a_posteriori" : 0.00032139811577416502,
							"sigma_abs" : 0.00038000000000000002,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00020273936760485477,
							"sigma_total" : 0.00038000000000000002,
							"standardized_residual" : -1.6184487306619428,
							"target_height" : 0.0,
							"to" : "CHSL_O",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : 141.51470782963733,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "PC2",
							"instrument_height" : 0.0,
							"line" : 46,
							"nabla" : 0.014551333737423112,
							"normalized_residual" : 0.012427995765365305,
							"number" : 47,
							"obs_azim" : -1.0915064273404842,
							"obs_length" : 266.49982354748437,
							"obs_redondancy" : 3.1509623174254986,
							"obs_zen" : 1.5708147032673705,
							"original_value" : 141.5147,
							"rank" : 47,
							"residual" : 7.8296373321801417e-06,
							"residual_std" : 0.012628548651485662,
							"sigma_a_posteriori" : 0.00061999502462692238,
							"sigma_abs" : 0.00063000000000000003,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00011183098603634783,
							"sigma_total" : 0.00063000000000000003,
							"standardized_residual" : 0.070013129720910408,
							"target_height" : 0.0,
							"to" : "BAT4",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						}
					],
					"params" : 
					{
						"PC2_G0_1" : 
						{
							"rank" : 31,
							"sigma" : 7.5203658396862689e-06,
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"value" : 2.9687710473766287
						}
					},
					"type" : "hz_unknown"
				}
			]
		},
		"PTHN" : 
		{
			"code" : 7,
			"code_name" : "2xy ",
			"comment" : "",
			"coord_compensated_cartesian" : 
			[
				-5876.4084285371036,
				-1652.38671544163,
				-2.9161915534892842
			],
			"coord_compensated_georef" : 
			[
				652015.41470041336,
				6860881.4211800573,
				0.0
			],
			"coord_compensated_latlong" : 
			[
				2.3461482688275015,
				48.846189972388927,
				0.0
			],
			"coord_init_latlong" : 
			[
				2.3461482015294819,
				48.846190231216212,
				0.0
			],
			"coord_read" : 
			[
				652015.41000000003,
				6860881.4500000002,
				0.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 2,
			"ellips" : 
			{
				"axes" : 
				[
					[
						0.12082690687286898,
						81.743919665372971,
						0.0
					],
					[
						0.046876819872451889,
						181.74391966537331,
						0.0
					],
					[
						0.0,
						0.0,
						100.0
					]
				],
				"matrix" : 
				[
					0.0092869324777293087,
					0.002296384125987018,
					0.0,
					0.0021769715150653035,
					0.0,
					0.0
				],
				"sigmas" : 
				[
					0.11664879989114185,
					0.056476854991895614,
					0.0
				]
			},
			"file_id" : 0,
			"nbr_active_obs" : 11,
			"number" : 6,
			"params" : 
			{
				"PTHN_x" : 
				{
					"rank" : 4,
					"sigma" : 0.11664879989114185,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : -5876.40842612283
				},
				"PTHN_y" : 
				{
					"rank" : 5,
					"sigma" : 0.056476854991895614,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : -1652.3867154952507
				}
			},
			"shift_from_read" : 
			[
				0.004700413323007524,
				-0.028819942846894264,
				0.0
			],
			"sigmas_init" : 
			[
				0.10000000000000001,
				0.10000000000000001,
				0.0
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 2,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : -1,
							"comment" : "",
							"computed_value" : -5876.40842612283,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "PTHN",
							"instrument_height" : 0.0,
							"line" : 10,
							"nabla" : 1.5353893666340928,
							"normalized_residual" : 0.049091728651546873,
							"number" : 12,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 7.1306752227069286,
							"obs_zen" : 0.0,
							"original_value" : -5876.4133352956951,
							"rank" : 12,
							"residual" : 0.0049091728651546873,
							"residual_std" : 0.050941553044063739,
							"sigma_a_posteriori" : 0.096368731846638453,
							"sigma_abs" : 0.10000000000000001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.026703324180159541,
							"sigma_total" : 0.10000000000000001,
							"standardized_residual" : 0.18384126380797872,
							"target_height" : 0.0,
							"to" : "PTHN",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -2,
							"comment" : "",
							"computed_value" : -1652.3867154952507,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "PTHN",
							"instrument_height" : 0.0,
							"line" : 10,
							"nabla" : 0.46354980308644878,
							"normalized_residual" : -0.28788524842411789,
							"number" : 13,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 78.230284849346958,
							"obs_zen" : 0.0,
							"original_value" : -1652.3579269704082,
							"rank" : 13,
							"residual" : -0.028788524842411789,
							"residual_std" : -0.61701118724794279,
							"sigma_a_posteriori" : 0.046658027337911571,
							"sigma_abs" : 0.10000000000000001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.088447885700759968,
							"sigma_total" : 0.10000000000000001,
							"standardized_residual" : -0.32548573224022731,
							"target_height" : 0.0,
							"to" : "PTHN",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						}
					],
					"params" : null,
					"type" : "simple"
				}
			]
		},
		"S1" : 
		{
			"code" : 7,
			"code_name" : "2xy ",
			"comment" : " Guilands pelouse ouest",
			"coord_compensated_cartesian" : 
			[
				-19.179977833471998,
				7.6860798975454596,
				-3.3420577577381039e-05
			],
			"coord_compensated_georef" : 
			[
				657883.87837062578,
				6862498.8244327782,
				0.0
			],
			"coord_compensated_latlong" : 
			[
				2.4259504060822725,
				48.861145563029581,
				0.0
			],
			"coord_init_latlong" : 
			[
				2.425950388533932,
				48.861145460125741,
				0.0
			],
			"coord_read" : 
			[
				657883.87699999998,
				6862498.8130000001,
				0.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 2,
			"ellips" : 
			{
				"axes" : 
				[
					[
						0.0090282081418647207,
						31.172591103910335,
						0.0
					],
					[
						0.0079535653956260954,
						131.17259110391038,
						0.0
					],
					[
						0.0,
						0.0,
						100.0
					]
				],
				"matrix" : 
				[
					4.5930509229863357e-05,
					5.1697283713196164e-06,
					0.0,
					5.2875542821192297e-05,
					0.0,
					0.0
				],
				"sigmas" : 
				[
					0.0082034164883211021,
					0.0088018011040056337,
					0.0
				]
			},
			"file_id" : 0,
			"nbr_active_obs" : 7,
			"number" : 0,
			"params" : 
			{
				"S1_x" : 
				{
					"rank" : 16,
					"sigma" : 0.0082034164883211021,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : -19.179977833428588
				},
				"S1_y" : 
				{
					"rank" : 17,
					"sigma" : 0.0088018011040056337,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 7.6860798972199182
				}
			},
			"shift_from_read" : 
			[
				0.0013706258032470942,
				0.011432778090238571,
				0.0
			],
			"sigmas_init" : 
			[
				0.01,
				0.01,
				0.0
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 2,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : -1,
							"comment" : " Guilands pelouse ouest",
							"computed_value" : -19.179977833428588,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "S1",
							"instrument_height" : 0.0,
							"line" : 1,
							"nabla" : 0.055758067980607583,
							"normalized_residual" : 0.12876485172697016,
							"number" : 0,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 54.069490770136653,
							"obs_zen" : 0.0,
							"original_value" : -19.181265481945857,
							"rank" : 0,
							"residual" : 0.0012876485172697016,
							"residual_std" : 0.18999698173389867,
							"sigma_a_posteriori" : 0.0067772051193588168,
							"sigma_abs" : 0.01,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.0073531959561905225,
							"sigma_total" : 0.01,
							"standardized_residual" : 0.17511413063671363,
							"target_height" : 0.0,
							"to" : "S1",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -2,
							"comment" : " Guilands pelouse ouest",
							"computed_value" : 7.6860798972199182,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "S1",
							"instrument_height" : 0.0,
							"line" : 1,
							"nabla" : 0.059725621323100157,
							"normalized_residual" : 1.144362554660816,
							"number" : 1,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 47.124457178807702,
							"obs_zen" : 0.0,
							"original_value" : 7.6746362716733101,
							"rank" : 1,
							"residual" : 0.01144362554660816,
							"residual_std" : 1.5737517249241295,
							"sigma_a_posteriori" : 0.0072715571111827415,
							"sigma_abs" : 0.01,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.0068647255719954097,
							"sigma_total" : 0.01,
							"standardized_residual" : 1.6670186486831076,
							"target_height" : 0.0,
							"to" : "S1",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						}
					],
					"params" : null,
					"type" : "simple"
				},
				{
					"nbr_active_obs" : 4,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : 7,
							"comment" : "",
							"computed_value" : -0.00045943698178196787,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "S1",
							"instrument_height" : 0.0,
							"line" : 13,
							"nabla" : 0.0053094685565164383,
							"normalized_residual" : -0.45943698178196785,
							"number" : 30,
							"obs_azim" : 2.7825571311480193,
							"obs_length" : 2235.3463378480874,
							"obs_redondancy" : 59.630109529701514,
							"obs_zen" : 1.5709504649216453,
							"original_value" : 0.0,
							"rank" : 30,
							"residual" : -0.00045943698178196787,
							"residual_std" : -0.72309800724687345,
							"sigma_a_posteriori" : 0.00063537304373335272,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00077220534529166211,
							"sigma_total" : 0.001,
							"standardized_residual" : -0.59496736792004257,
							"target_height" : 0.0,
							"to" : "CHSL_E",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : 105.27429034295288,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "S1",
							"instrument_height" : 0.0,
							"line" : 14,
							"nabla" : 0.00517022793974876,
							"normalized_residual" : -0.20965704710372832,
							"number" : 31,
							"obs_azim" : -1.8469762734458348,
							"obs_length" : 6087.9359367557709,
							"obs_redondancy" : 62.885183559072452,
							"obs_zen" : 1.5712161199414005,
							"original_value" : 105.2745,
							"rank" : 31,
							"residual" : -0.00020965704710372834,
							"residual_std" : -0.3441405165352393,
							"sigma_a_posteriori" : 0.00060921930731820662,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00079300178788620928,
							"sigma_total" : 0.001,
							"standardized_residual" : -0.26438407870754105,
							"target_height" : 0.0,
							"to" : "PTHN",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : 120.79577297804741,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "S1",
							"instrument_height" : 0.0,
							"line" : 15,
							"nabla" : 0.0050870017191667061,
							"normalized_residual" : 0.87297804734216289,
							"number" : 32,
							"obs_azim" : -1.603165394349662,
							"obs_length" : 9650.6698021088268,
							"obs_redondancy" : 64.959690139468862,
							"obs_zen" : 1.57146178801465,
							"original_value" : 120.7949,
							"rank" : 32,
							"residual" : 0.00087297804734216291,
							"residual_std" : 1.4747532221331692,
							"sigma_a_posteriori" : 0.00059194856077645079,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00080597574491710891,
							"sigma_total" : 0.001,
							"standardized_residual" : 1.0831319091766773,
							"target_height" : 0.0,
							"to" : "TFLE",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : -148.66220388401851,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "S1",
							"instrument_height" : 0.0,
							"line" : 16,
							"nabla" : 0.010485845269356137,
							"normalized_residual" : -0.20388401851300988,
							"number" : 33,
							"obs_azim" : 0.44738391002475003,
							"obs_length" : 347.66805220427523,
							"obs_redondancy" : 15.288357288410648,
							"obs_zen" : 1.5708203002164167,
							"original_value" : -148.66200000000001,
							"rank" : 33,
							"residual" : -0.00020388401851300988,
							"residual_std" : -0.22151933198053403,
							"sigma_a_posteriori" : 0.0009203892802047912,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00039100329011928586,
							"sigma_total" : 0.001,
							"standardized_residual" : -0.52143811488340597,
							"target_height" : 0.0,
							"to" : "BAT4",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						}
					],
					"params" : 
					{
						"S1_G0_1" : 
						{
							"rank" : 18,
							"sigma" : 1.1257243076191505e-05,
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"value" : 2.782564347967253
						}
					},
					"type" : "hz_unknown"
				}
			]
		},
		"S4" : 
		{
			"code" : 7,
			"code_name" : "2xy ",
			"comment" : " Guilands butte sud-est",
			"coord_compensated_cartesian" : 
			[
				252.83467265804387,
				93.895227029208314,
				-0.0056935995717708465
			],
			"coord_compensated_georef" : 
			[
				658156.4840383596,
				6862583.0457473686,
				0.0
			],
			"coord_compensated_latlong" : 
			[
				2.4296576446113578,
				48.861920724773348,
				0.0
			],
			"coord_init_latlong" : 
			[
				2.4296576033708792,
				48.861920708862023,
				0.0
			],
			"coord_read" : 
			[
				658156.48100000003,
				6862583.0439999998,
				0.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 2,
			"ellips" : 
			{
				"axes" : 
				[
					[
						0.012090346838268356,
						169.72180981430651,
						0.0
					],
					[
						0.0080825907140620306,
						69.721809814306582,
						0.0
					],
					[
						0.0,
						0.0,
						100.0
					]
				],
				"matrix" : 
				[
					5.6156187556515392e-05,
					-2.2461679154373819e-05,
					0.0,
					8.8198829466114376e-05,
					0.0,
					0.0
				],
				"sigmas" : 
				[
					0.0090707446015430397,
					0.011367776902026411,
					0.0
				]
			},
			"file_id" : 0,
			"nbr_active_obs" : 6,
			"number" : 1,
			"params" : 
			{
				"S4_x" : 
				{
					"rank" : 22,
					"sigma" : 0.0090707446015430397,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 252.83467265787863
				},
				"S4_y" : 
				{
					"rank" : 23,
					"sigma" : 0.011367776902026411,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 93.89522703195648
				}
			},
			"shift_from_read" : 
			[
				0.0030383595731109381,
				0.0017473688349127769,
				0.0
			],
			"sigmas_init" : 
			[
				0.01,
				0.01,
				0.0
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 2,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : -1,
							"comment" : " Guilands butte sud-est",
							"computed_value" : 252.83467265787863,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "S4",
							"instrument_height" : 0.0,
							"line" : 2,
							"nabla" : 0.061919822268316556,
							"normalized_residual" : 0.3025892456520296,
							"number" : 2,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 43.843812443484623,
							"obs_zen" : 0.0,
							"original_value" : 252.83164676542211,
							"rank" : 2,
							"residual" : 0.003025892456520296,
							"residual_std" : 0.40378918315508189,
							"sigma_a_posteriori" : 0.0074937432272873744,
							"sigma_abs" : 0.01,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.0066214660343072527,
							"sigma_total" : 0.01,
							"standardized_residual" : 0.4569822514896989,
							"target_height" : 0.0,
							"to" : "S4",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -2,
							"comment" : " Guilands butte sud-est",
							"computed_value" : 93.89522703195648,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "S4",
							"instrument_height" : 0.0,
							"line" : 2,
							"nabla" : 0.11934969503060192,
							"normalized_residual" : 0.17695927466547801,
							"number" : 3,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 11.801170533885641,
							"obs_zen" : 0.0,
							"original_value" : 93.893457439209826,
							"rank" : 3,
							"residual" : 0.0017695927466547801,
							"residual_std" : 0.18842647291379114,
							"sigma_a_posteriori" : 0.0093914231864033453,
							"sigma_abs" : 0.01,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.0034352831810326267,
							"sigma_total" : 0.01,
							"standardized_residual" : 0.51512281619905653,
							"target_height" : 0.0,
							"to" : "S4",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						}
					],
					"params" : null,
					"type" : "simple"
				},
				{
					"nbr_active_obs" : 4,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : 7,
							"comment" : "",
							"computed_value" : -0.00053689567056336765,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "S4",
							"instrument_height" : 0.0,
							"line" : 34,
							"nabla" : 0.0056902564786754191,
							"normalized_residual" : -0.53689567056336762,
							"number" : 41,
							"obs_azim" : 2.6449532430083633,
							"obs_length" : 2357.0019427300113,
							"obs_redondancy" : 51.916335412789863,
							"obs_zen" : 1.5709588536744412,
							"original_value" : 0.0,
							"rank" : 41,
							"residual" : -0.00053689567056336765,
							"residual_std" : -0.77426766459159102,
							"sigma_a_posteriori" : 0.00069342385729948854,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00072052991202856988,
							"sigma_total" : 0.001,
							"standardized_residual" : -0.74514001653560646,
							"target_height" : 0.0,
							"to" : "ANFN",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : 16.885131163834451,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "S4",
							"instrument_height" : 0.0,
							"line" : 35,
							"nabla" : 0.0051978420185608311,
							"normalized_residual" : -0.36883616557159643,
							"number" : 42,
							"obs_azim" : 2.9101926966418472,
							"obs_length" : 2238.6906171423725,
							"obs_redondancy" : 62.218790199566079,
							"obs_zen" : 1.5709506955264019,
							"original_value" : 16.8855,
							"rank" : 42,
							"residual" : -0.00036883616557159641,
							"residual_std" : -0.60006123047157689,
							"sigma_a_posteriori" : 0.00061466421565301759,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00078878888303250108,
							"sigma_total" : 0.001,
							"standardized_residual" : -0.4675980778958303,
							"target_height" : 0.0,
							"to" : "CHSL_E",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : 39.473341045131356,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "S4",
							"instrument_height" : 0.0,
							"line" : 36,
							"nabla" : 0.0050891958298276679,
							"normalized_residual" : 0.84104513132796388,
							"number" : 43,
							"obs_azim" : -3.0181778394336054,
							"obs_length" : 7828.8993878833944,
							"obs_redondancy" : 64.903689926805157,
							"obs_zen" : 1.5713361679534008,
							"original_value" : 39.472499999999997,
							"rank" : 43,
							"residual" : 0.00084104513132796392,
							"residual_std" : 1.4196738143441749,
							"sigma_a_posteriori" : 0.00059242138780765544,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.0008056282636973777,
							"sigma_total" : 0.001,
							"standardized_residual" : 1.0439617987929606,
							"target_height" : 0.0,
							"to" : "VITRY",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : -199.66553531329524,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "S4",
							"instrument_height" : 0.0,
							"line" : 37,
							"nabla" : 0.014656717085664205,
							"normalized_residual" : 0.064686704750456944,
							"number" : 44,
							"obs_azim" : -0.49137721803077394,
							"obs_length" : 257.7364680796689,
							"obs_redondancy" : 7.8251794131579562,
							"obs_zen" : 1.5708140989933221,
							"original_value" : -199.66560000000001,
							"rank" : 44,
							"residual" : 6.468670475045695e-05,
							"residual_std" : 0.067376566796716081,
							"sigma_a_posteriori" : 0.00096007718745339454,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.00027973522147126833,
							"sigma_total" : 0.001,
							"standardized_residual" : 0.23124261725154596,
							"target_height" : 0.0,
							"to" : "BAT4",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						}
					],
					"params" : 
					{
						"S4_G0_1" : 
						{
							"rank" : 24,
							"sigma" : 1.1249501088546116e-05,
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"value" : 2.6449616765458352
						}
					},
					"type" : "hz_unknown"
				}
			]
		},
		"TFLE" : 
		{
			"code" : 7,
			"code_name" : "2xy ",
			"comment" : "",
			"coord_compensated_cartesian" : 
			[
				-9664.795374930407,
				-304.64259476774555,
				-7.3159087968723782
			],
			"coord_compensated_georef" : 
			[
				648237.26651848108,
				6862256.3140357342,
				0.0
			],
			"coord_compensated_latlong" : 
			[
				2.2945013938925949,
				48.858261799616756,
				0.0
			],
			"coord_init_latlong" : 
			[
				2.2945014442681746,
				48.858261583747058,
				0.0
			],
			"coord_read" : 
			[
				648237.27000000002,
				6862256.29,
				0.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 2,
			"ellips" : 
			{
				"axes" : 
				[
					[
						0.12100351158021706,
						97.271767485000566,
						0.0
					],
					[
						0.066094505450737487,
						197.27176748499912,
						0.0
					],
					[
						0.0,
						0.0,
						100.0
					]
				],
				"matrix" : 
				[
					0.0099804019961528736,
					0.00030011928098865731,
					0.0,
					0.0029944219266534755,
					0.0,
					0.0
				],
				"sigmas" : 
				[
					0.12092557141548156,
					0.066236996032131193,
					0.0
				]
			},
			"file_id" : 0,
			"nbr_active_obs" : 10,
			"number" : 5,
			"params" : 
			{
				"TFLE_x" : 
				{
					"rank" : 6,
					"sigma" : 0.12092557141548156,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : -9664.7953641838212
				},
				"TFLE_y" : 
				{
					"rank" : 7,
					"sigma" : 0.066236996032131193,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : -304.6425947745156
				}
			},
			"shift_from_read" : 
			[
				-0.0034815189428627491,
				0.024035734124481678,
				0.0
			],
			"sigmas_init" : 
			[
				0.10000000000000001,
				0.10000000000000001,
				0.0
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 2,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : -1,
							"comment" : "",
							"computed_value" : -9664.7953641838212,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "TFLE",
							"instrument_height" : 0.0,
							"line" : 9,
							"normalized_residual" : -0.036549507767631439,
							"number" : 10,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 0.19598003847125511,
							"obs_zen" : 0.0,
							"original_value" : -9664.7917092330445,
							"rank" : 10,
							"residual" : -0.0036549507767631439,
							"residual_std" : -0.036585375365941697,
							"sigma_a_posteriori" : 0.099901961923442098,
							"sigma_abs" : 0.10000000000000001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.10000000000000001,
							"target_height" : 0.0,
							"to" : "TFLE",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -2,
							"comment" : "",
							"computed_value" : -304.6425947745156,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "TFLE",
							"instrument_height" : 0.0,
							"line" : 9,
							"nabla" : 0.4898485964503923,
							"normalized_residual" : 0.24012581884051087,
							"number" : 11,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 70.055780733465255,
							"obs_zen" : 0.0,
							"original_value" : -304.66660735639965,
							"rank" : 11,
							"residual" : 0.024012581884051087,
							"residual_std" : 0.4388159064245209,
							"sigma_a_posteriori" : 0.05472131144858898,
							"sigma_abs" : 0.10000000000000001,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.083699331379327793,
							"sigma_total" : 0.10000000000000001,
							"standardized_residual" : 0.28689096422079374,
							"target_height" : 0.0,
							"to" : "TFLE",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						}
					],
					"params" : null,
					"type" : "simple"
				}
			]
		},
		"VITRY" : 
		{
			"code" : 7,
			"code_name" : "2xy ",
			"comment" : "",
			"coord_compensated_cartesian" : 
			[
				-710.91685720283897,
				-7675.45842810658,
				-4.6625631736615105
			],
			"coord_compensated_georef" : 
			[
				657136.44433898933,
				6854821.8960469756,
				0.0
			],
			"coord_compensated_latlong" : 
			[
				2.4165362944201987,
				48.792056076099264,
				0.0
			],
			"coord_init_latlong" : 
			[
				2.4165363034223497,
				48.792056075720701,
				0.0
			],
			"coord_read" : 
			[
				657136.44499999995,
				6854821.8959999997,
				0.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 2,
			"ellips" : 
			{
				"axes" : 
				[
					[
						0.014523655448994623,
						0.74707799856763324,
						0.0
					],
					[
						0.013175893540127456,
						100.74707799856766,
						0.0
					],
					[
						0.0,
						0.0,
						100.0
					]
				],
				"matrix" : 
				[
					0.00011849083298128917,
					2.9898098262656277e-07,
					0.0,
					0.00014396370933933924,
					0.0,
					0.0
				],
				"sigmas" : 
				[
					0.013176088625316709,
					0.014523478464874841,
					0.0
				]
			},
			"file_id" : 0,
			"nbr_active_obs" : 7,
			"number" : 10,
			"params" : 
			{
				"VITRY_x" : 
				{
					"rank" : 8,
					"sigma" : 0.013176088625316709,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : -710.91685720134774
				},
				"VITRY_y" : 
				{
					"rank" : 9,
					"sigma" : 0.014523478464874841,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : -7675.4584335300005
				}
			},
			"shift_from_read" : 
			[
				-0.0006610106211155653,
				4.6975910663604736e-05,
				0.0
			],
			"sigmas_init" : 
			[
				0.010999999999999999,
				0.012,
				0.0
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 2,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : -1,
							"comment" : "",
							"computed_value" : -710.91685720134774,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "VITRY",
							"instrument_height" : 0.0,
							"line" : 14,
							"nabla" : 0.31318751568525532,
							"normalized_residual" : -0.060130539426691859,
							"number" : 20,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 2.0736917510006836,
							"obs_zen" : 0.0,
							"original_value" : -710.91619576541405,
							"rank" : 20,
							"residual" : -0.00066143593369361042,
							"residual_std" : -0.060763867600510467,
							"sigma_a_posteriori" : 0.010885349465280808,
							"sigma_abs" : 0.010999999999999999,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.0015840350433973416,
							"sigma_total" : 0.010999999999999999,
							"standardized_residual" : -0.41756395254678397,
							"target_height" : 0.0,
							"to" : "VITRY",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -2,
							"comment" : "",
							"computed_value" : -7675.4584335300005,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "VITRY",
							"instrument_height" : 0.0,
							"line" : 14,
							"normalized_residual" : 0.0035153174546091273,
							"number" : 21,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 0.025201847681088907,
							"obs_zen" : 0.0,
							"original_value" : -7675.45847571381,
							"rank" : 21,
							"residual" : 4.2183809455309529e-05,
							"residual_std" : 0.00351576050082797,
							"sigma_a_posteriori" : 0.011998487793857159,
							"sigma_abs" : 0.012,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.012,
							"target_height" : 0.0,
							"to" : "VITRY",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						}
					],
					"params" : null,
					"type" : "simple"
				}
			]
		}
	}
}
